name: hyper_ui
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  uuid: ^4.0.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.2.0
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  blur: ^3.1.0
  flutter_svg: ^2.0.5
  custom_clippers: ^2.0.0
  badges: ^3.1.1
  flutter_markdown: ^0.6.12
  dotted_border: ^2.0.0+3
  faker_dart: ^0.2.1
  syncfusion_flutter_charts: ^25.1.35
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  flutter_animate: ^4.1.1+1
  dio: ^5.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.1
  screenshot: ^2.1.0
  syncfusion_flutter_calendar: ^25.1.35
  google_maps_flutter: ^2.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
